### ISSUE TITLE
cosnsume slim api 

### ISSUE THREAD

**Issue by cissemy** [donwibier/DXDevExtremeWebAPI#3]
Hi,
How can I consume a web api like :
http://php.8bl2.com/restapi/index.php/user/1
http://php.8bl2.com/restapi/index.php/users

**Comment by donwibier** [comment]
If you want to customize the endpoints, there is property for this: **controllerEndPoint**. 
It defaults to /api. (This is what's used by WebAPI)

You should be able to change it to **'/restapi/index.php'** and use user and users as controllerName.
In your case, you could try somethings like:
```
var client = new DX.WebAPI.Client('http://php.8bl2.com', globalEventsObj);
client.controllerEndPoint = '/restapi/index.php';
client.get('users', '', null, 
                function(a, s) { /* success code /* }, 
                function(e, s) { /* error code */}
);
```
